openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
paths:
  /:
    post:
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Order created
components:
  schemas:
    OrderRequest:
      type: object
      properties:
        order_number:
          type: string
        customer:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        items:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
              qty:
                type: integer
              unit_price:
                type: number
